name: "Be Blue V Uniform"

base:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Skeleton.uasset

costume:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_BeBlue.uasset

hair:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Hair.uasset

face:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Face.uasset

battle_physics: true