name: "Chagall Cafe Uniform"

base:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Skeleton.uasset

costume:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Cafe.uasset

hair:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Hair_Noclip.uasset

face:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Face.uasset

battle_physics: true