name: "Butler Suit"
display_name: "Knee-High Maid"

base:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Skeleton.uasset

costume:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Maid_Outfit.uasset

hair:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Hair.uasset

face:
  mesh_path: /Game/Xrd777/Characters/Player/FemC/Femc_Face.uasset

battle_physics: true